import React, { useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { toast } from "react-toastify";
import { ArrowRight, BriefcaseBusiness, Building2, CheckCircle2, Eye, EyeOff, Mail, ShieldCheck, UserRound } from "lucide-react";
import API from "../services/api";

const Signup = () => {
  const navigate = useNavigate();
  const [formData, setFormData] = useState({ name: "", email: "", password: "", role: "jobseeker" });
  const [showPassword, setShowPassword] = useState(false);
  const [loading, setLoading] = useState(false);
  const update = (event) => setFormData({ ...formData, [event.target.name]: event.target.value });
  const submit = async (event) => { event.preventDefault(); setLoading(true); try { const { data } = await API.post("/auth/signup", formData); localStorage.setItem("token", data.token); localStorage.setItem("role", data.user.role); localStorage.setItem("userId", data.user.id); toast.success("Your JobDekho account is ready"); navigate(data.user.role === "recruiter" ? "/recruiter" : "/applications"); } catch (error) { toast.error(error.response?.data?.error || "We couldn't create your account. Please try again."); } finally { setLoading(false); } };
  return <section className="jd-auth-page jd-auth-signup"><div className="jd-auth-orb jd-auth-orb-one" /><div className="jd-auth-orb jd-auth-orb-two" /><div className="jd-auth-layout"><aside className="jd-auth-aside"><Link to="/" className="jd-auth-brand"><span><BriefcaseBusiness size={18} /></span> JobDekho</Link><div><p className="jd-auth-kicker">Start something meaningful</p><h1>A career space that <em>works with you.</em></h1><p>Whether you&apos;re discovering a new role or building a team, JobDekho keeps every important hiring moment clear and connected.</p></div><div className="jd-auth-proof"><span><CheckCircle2 size={17} /> Free to create an account</span><span><CheckCircle2 size={17} /> Built for job seekers and employers</span><span><CheckCircle2 size={17} /> Manage your journey in one workspace</span></div></aside><main className="jd-auth-card jd-auth-card-signup"><div className="jd-auth-card-head"><span className="jd-auth-icon"><UserRound size={21} /></span><div><p>Join JobDekho</p><h2>Create your account</h2></div></div><form onSubmit={submit} className="jd-auth-form"><label>Full name <span className="jd-auth-input"><UserRound size={17} /><input name="name" value={formData.name} onChange={update} placeholder="Your full name" autoComplete="name" required /></span></label><label>Email address <span className="jd-auth-input"><Mail size={17} /><input type="email" name="email" value={formData.email} onChange={update} placeholder="you@example.com" autoComplete="email" required /></span></label><label>Password <span className="jd-auth-input"><ShieldCheck size={17} /><input type={showPassword ? "text" : "password"} name="password" value={formData.password} onChange={update} placeholder="Create a secure password" autoComplete="new-password" minLength="6" required /><button type="button" aria-label={showPassword ? "Hide password" : "Show password"} onClick={() => setShowPassword((show) => !show)}>{showPassword ? <EyeOff size={17} /> : <Eye size={17} />}</button></span></label><fieldset className="jd-role-select"><legend>I want to</legend><button type="button" className={formData.role === "jobseeker" ? "active" : ""} onClick={() => setFormData({ ...formData, role: "jobseeker" })}><UserRound size={17} /><span>Find a job<small>Explore and apply</small></span></button><button type="button" className={formData.role === "recruiter" ? "active" : ""} onClick={() => setFormData({ ...formData, role: "recruiter" })}><Building2 size={17} /><span>Hire people<small>Post and manage roles</small></span></button></fieldset><button className="jd-auth-submit" type="submit" disabled={loading}>{loading ? "Creating your account…" : <>Create account <ArrowRight size={17} /></>}</button></form><p className="jd-auth-switch">Already have an account? <Link to="/login">Sign in</Link></p></main></div></section>;
};

export default Signup;
